apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: elk-prometheus
    meta.helm.sh/release-namespace: logging-monitoring

  generation: 1
  labels:
    app: prometheus-elasticsearch-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-elasticsearch-exporter-5.2.0
    heritage: Helm
    release: elk-prometheus
  name: elk-prometheus-prometheus-elasticsearch-exporter
  namespace: logging-monitoring

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-elasticsearch-exporter
      release: elk-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-elasticsearch-exporter
        release: elk-prometheus
    spec:
      containers:
      - command:
        - elasticsearch_exporter
        - --log.format=logfmt
        - --log.level=info
        - --es.uri=http://localhost:9200
        - --es.all
        - --es.indices
        - --es.indices_settings
        - --es.indices_mappings
        - --es.shards
        - --es.snapshots
        - --es.timeout=30s
        - --web.listen-address=:9108
        - --web.telemetry-path=/metrics
        image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.5.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 20
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: exporter
        ports:
        - containerPort: 9108
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1

  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1